Fixes tests and upgrades base jenkins to 2.387.3
Tests failed due to class jakarta.annotation.PostConstruct not being found.

This is because ssc-restapi-client depends on jakarta.annotation-api v1
overriding jenkins depending on jakarta.annotation-api v2.

jakarta.annotation-api v2 uses jakarta package and v1 uses the old javax
package.

Adding an exclusion for jakarta.annotation:jakarta.annotation-api resolves
this, but now fails with:

java.lang.IllegalStateException: Couldn't locate either of bouncy castle FIPS or non fips provider, available providers areSUN,SunRsaSign,SunEC,SunJSSE,SunJCE,SunJGSS,SunSASL,XMLDSig,SunPCSC,JdkLDAP,JdkSASL,SunPKCS11.
	at jenkins.bouncycastle.api.PEMEncodable.<clinit>(PEMEncodable.java:96)

Bumping base jenkins to 2.387.3 and parent pom to  4.66 resolves this.

https://github.com/jenkinsci/jenkins/pull/6161
https://github.com/jenkinsci/bouncycastle-api-plugin/pull/46/